# Production environment configuration
environment: prod
app_name: anomaly-detector

# AWS Configuration
aws:
  region: us-east-1
  profile: prod-profile
  
# S3 Configuration
s3:
  model_bucket_name: anomaly-detector-models-prod
  data_bucket_name: anomaly-detector-data-prod
  log_bucket_name: anomaly-detector-logs-prod
  compliance_bucket_name: anomaly-detector-compliance-prod
  # S3 transfer tuning (optional)
  # - multipart_threshold: bytes above which multipart uploads are used
  # - transfer_config_kwargs: forwarded to boto3.s3.transfer.TransferConfig
  transfer:
    multipart_threshold: 8388608  # 8 MiB
    transfer_config_kwargs:
      max_concurrency: 10
      multipart_chunksize: 8388608

# Data Retention & Immutability Policies
data_retention:
  raw_security_logs:
    retention_years: 7
    immutable: true
    mfa_delete: true
    lifecycle_transitions:
      - days: 30
        storage_class: "STANDARD_IA"
      - days: 365
        storage_class: "GLACIER"
      - days: 1095  # 3 years
        storage_class: "DEEP_ARCHIVE"
    
  compliance_outputs:
    retention_years: 5
    immutable: true
    lifecycle_transitions:
      - days: 90
        storage_class: "STANDARD_IA"
      - days: 730  # 2 years
        storage_class: "GLACIER"
  
  model_artifacts:
    retention_years: 3
    immutable: false  # Allow model updates
    lifecycle_transitions:
      - days: 30
        storage_class: "STANDARD_IA"
      - days: 90
        storage_class: "GLACIER"

# KMS Configuration
kms:
  key_alias: alias/anomaly-detector-prod
  
# VPC Configuration (required for prod)
vpc:
  vpc_id: vpc-12345678  # Existing VPC ID
  private_subnets: 
    - subnet-12345678
    - subnet-87654321
  
# Model Configuration
model:
  ner_model_name: "distilbert-base-uncased"
  anomaly_threshold: 2.5
  batch_size: 64
  
# Logging
logging:
  level: INFO
  structured: true
  
# Feature Flags
features:
  enable_training: false  # Training in dedicated environment
  enable_sagemaker: true
  enable_vpc_endpoints: true
  
# Alerts
alerts:
  sns_topic_name: anomaly-detector-alerts-prod
  email_endpoints:
    - security-team@company.com
    - ops-team@company.com