name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Run detect-secrets scan
        id: scan
        run: |
          detect-secrets scan > .secrets.baseline || true
          detect-secrets audit --baseline .secrets.baseline || true
          # exit non-zero if any potential secrets are found
          detect-secrets scan | grep "Potential Secrets" && (echo "Potential secrets detected" && exit 1) || true

      - name: Upload baseline
        uses: actions/upload-artifact@v4
        with:
          name: secrets-baseline
          path: .secrets.baseline
